//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DeskAppWS_Vianello.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebsrvSoap", Namespace="http://tempuri.org/")]
    public partial class Websrv : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Elenco_BreveOperationCompleted;
        
        private System.Threading.SendOrPostCallback Elenco_EstesoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Websrv() {
            this.Url = global::DeskAppWS_Vianello.Properties.Settings.Default.DeskAppWS_Vianello_localhost_Websrv;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Elenco_BreveCompletedEventHandler Elenco_BreveCompleted;
        
        /// <remarks/>
        public event Elenco_EstesoCompletedEventHandler Elenco_EstesoCompleted;
        
        /// <remarks/>
        public event ModificaCompletedEventHandler ModificaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Elenco_Breve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Elenco_Breve() {
            object[] results = this.Invoke("Elenco_Breve", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Elenco_BreveAsync() {
            this.Elenco_BreveAsync(null);
        }
        
        /// <remarks/>
        public void Elenco_BreveAsync(object userState) {
            if ((this.Elenco_BreveOperationCompleted == null)) {
                this.Elenco_BreveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnElenco_BreveOperationCompleted);
            }
            this.InvokeAsync("Elenco_Breve", new object[0], this.Elenco_BreveOperationCompleted, userState);
        }
        
        private void OnElenco_BreveOperationCompleted(object arg) {
            if ((this.Elenco_BreveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Elenco_BreveCompleted(this, new Elenco_BreveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Elenco_Esteso", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Elenco_Esteso() {
            object[] results = this.Invoke("Elenco_Esteso", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Elenco_EstesoAsync() {
            this.Elenco_EstesoAsync(null);
        }
        
        /// <remarks/>
        public void Elenco_EstesoAsync(object userState) {
            if ((this.Elenco_EstesoOperationCompleted == null)) {
                this.Elenco_EstesoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnElenco_EstesoOperationCompleted);
            }
            this.InvokeAsync("Elenco_Esteso", new object[0], this.Elenco_EstesoOperationCompleted, userState);
        }
        
        private void OnElenco_EstesoOperationCompleted(object arg) {
            if ((this.Elenco_EstesoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Elenco_EstesoCompleted(this, new Elenco_EstesoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Modifica", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Modifica(string x, string y) {
            this.Invoke("Modifica", new object[] {
                        x,
                        y});
        }
        
        /// <remarks/>
        public void ModificaAsync(string x, string y) {
            this.ModificaAsync(x, y, null);
        }
        
        /// <remarks/>
        public void ModificaAsync(string x, string y, object userState) {
            if ((this.ModificaOperationCompleted == null)) {
                this.ModificaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificaOperationCompleted);
            }
            this.InvokeAsync("Modifica", new object[] {
                        x,
                        y}, this.ModificaOperationCompleted, userState);
        }
        
        private void OnModificaOperationCompleted(object arg) {
            if ((this.ModificaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Elenco_BreveCompletedEventHandler(object sender, Elenco_BreveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Elenco_BreveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Elenco_BreveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Elenco_EstesoCompletedEventHandler(object sender, Elenco_EstesoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Elenco_EstesoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Elenco_EstesoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ModificaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591